services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: restraunts_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./back/restaurants_booking_app
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/restraunts_booking
    depends_on:
      - db
    volumes:
      - ./back/restaurants_booking_app:/app

  frontend:
    build: ./front/restraunt-booking-frontend
    container_name: frontend
    ports:
      - "8018:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8000

volumes:
  db-data: