"""restraunt fix open close

Revision ID: 184639b5b7ad
Revises: c4c7e190cc6b
Create Date: 2025-03-18 22:42:15.687757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184639b5b7ad'
down_revision: Union[str, None] = 'c4c7e190cc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurant', sa.Column('restaurant_close_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Restaurant', 'restaurant_close_minutes')
    # ### end Alembic commands ###
