"""fixed 1 more model

Revision ID: 3620e1c81f05
Revises: ca8c38da7087
Create Date: 2025-03-05 17:01:42.386508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3620e1c81f05'
down_revision: Union[str, None] = 'ca8c38da7087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
