"""fixed time model

Revision ID: 6c017ad446fc
Revises: 1fe039232952
Create Date: 2025-03-06 12:16:21.752228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c017ad446fc'
down_revision: Union[str, None] = '1fe039232952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Booking', 'booking_start_time',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('Booking', 'booking_end_time',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Booking', 'booking_end_time',
               existing_type=sa.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('Booking', 'booking_start_time',
               existing_type=sa.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
