"""restraunt another 1 fix open close

Revision ID: 7896936de5ec
Revises: 99502c4c6668
Create Date: 2025-03-18 22:48:32.799695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7896936de5ec'
down_revision: Union[str, None] = '99502c4c6668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Restaurant', 'restaurant_open_hours',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('Restaurant', 'restaurant_open_minutes',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('Restaurant', 'restaurant_close_hours',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('Restaurant', 'restaurant_close_minutes',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Restaurant', 'restaurant_close_minutes',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Restaurant', 'restaurant_close_hours',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Restaurant', 'restaurant_open_minutes',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Restaurant', 'restaurant_open_hours',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
