"""add geo model

Revision ID: 7cd28800eb7d
Revises: 4d025cd8edd9
Create Date: 2025-03-13 02:42:34.118843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd28800eb7d'
down_revision: Union[str, None] = '4d025cd8edd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurant', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('Restaurant', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Restaurant', 'longitude')
    op.drop_column('Restaurant', 'latitude')
    # ### end Alembic commands ###
