"""new migration

Revision ID: 88006c44f2d8
Revises: 
Create Date: 2025-03-05 16:47:07.016241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88006c44f2d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Booking_Status',
    sa.Column('booking_status_id', sa.Integer(), nullable=False),
    sa.Column('booking_status_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('booking_status_id'),
    sa.UniqueConstraint('booking_status_name')
    )
    op.create_index(op.f('ix_Booking_Status_booking_status_id'), 'Booking_Status', ['booking_status_id'], unique=False)
    op.create_table('Restaurant',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=120), nullable=False),
    sa.Column('restaurant_address', sa.String(length=100), nullable=False),
    sa.Column('restaurant_phone', sa.String(length=12), nullable=True),
    sa.Column('restaurant_created_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('restaurant_id'),
    sa.UniqueConstraint('restaurant_name'),
    sa.UniqueConstraint('restaurant_phone')
    )
    op.create_index(op.f('ix_Restaurant_restaurant_id'), 'Restaurant', ['restaurant_id'], unique=False)
    op.create_table('User_Role',
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('user_role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('user_role_name')
    )
    op.create_index(op.f('ix_User_Role_user_role_id'), 'User_Role', ['user_role_id'], unique=False)
    op.create_table('Floor',
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(length=100), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('floor_created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['Restaurant.restaurant_id'], ),
    sa.PrimaryKeyConstraint('floor_id')
    )
    op.create_index(op.f('ix_Floor_floor_id'), 'Floor', ['floor_id'], unique=False)
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=12), nullable=True),
    sa.Column('user_hash_password', sa.String(length=255), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('user_created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['User_Role.user_role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_phone')
    )
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=False)
    op.create_table('Table',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('table_number', sa.String(length=5), nullable=False),
    sa.Column('table_capacity', sa.Integer(), nullable=False),
    sa.Column('table_created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['Floor.floor_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_index(op.f('ix_Table_table_id'), 'Table', ['table_id'], unique=False)
    op.create_table('Booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('booking_start_time', sa.Date(), nullable=True),
    sa.Column('booking_end_time', sa.Date(), nullable=True),
    sa.Column('booking_status_id', sa.Integer(), nullable=True),
    sa.Column('booking_created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['booking_status_id'], ['Booking_Status.booking_status_id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['Table.table_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_Booking_booking_id'), 'Booking', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Booking_booking_id'), table_name='Booking')
    op.drop_table('Booking')
    op.drop_index(op.f('ix_Table_table_id'), table_name='Table')
    op.drop_table('Table')
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Floor_floor_id'), table_name='Floor')
    op.drop_table('Floor')
    op.drop_index(op.f('ix_User_Role_user_role_id'), table_name='User_Role')
    op.drop_table('User_Role')
    op.drop_index(op.f('ix_Restaurant_restaurant_id'), table_name='Restaurant')
    op.drop_table('Restaurant')
    op.drop_index(op.f('ix_Booking_Status_booking_status_id'), table_name='Booking_Status')
    op.drop_table('Booking_Status')
    # ### end Alembic commands ###
