"""restraunt open close

Revision ID: c4c7e190cc6b
Revises: 7cd28800eb7d
Create Date: 2025-03-18 22:40:54.894591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c7e190cc6b'
down_revision: Union[str, None] = '7cd28800eb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurant', sa.Column('restaurant_open_hours', sa.Integer(), nullable=True))
    op.add_column('Restaurant', sa.Column('restaurant_open_minutes', sa.Integer(), nullable=True))
    op.add_column('Restaurant', sa.Column('restaurant_close_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Restaurant', 'restaurant_close_hours')
    op.drop_column('Restaurant', 'restaurant_open_minutes')
    op.drop_column('Restaurant', 'restaurant_open_hours')
    # ### end Alembic commands ###
