"""fixed booking  model

Revision ID: e942460a12b2
Revises: 68bdbb85cb76
Create Date: 2025-03-09 23:49:49.030536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e942460a12b2'
down_revision: Union[str, None] = '68bdbb85cb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Booking', sa.Column('booking_start_hours', sa.Integer(), nullable=True))
    op.add_column('Booking', sa.Column('booking_end_hours', sa.Integer(), nullable=True))
    op.add_column('Booking', sa.Column('booking_start_minutes', sa.Integer(), nullable=True))
    op.add_column('Booking', sa.Column('booking_end_minutes', sa.Integer(), nullable=True))
    op.drop_column('Booking', 'booking_end_time')
    op.drop_column('Booking', 'booking_start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Booking', sa.Column('booking_start_time', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('Booking', sa.Column('booking_end_time', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('Booking', 'booking_end_minutes')
    op.drop_column('Booking', 'booking_start_minutes')
    op.drop_column('Booking', 'booking_end_hours')
    op.drop_column('Booking', 'booking_start_hours')
    # ### end Alembic commands ###
