"""admin added

Revision ID: ee0e98a5f734
Revises: 88006c44f2d8
Create Date: 2025-03-05 16:48:01.396718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0e98a5f734'
down_revision: Union[str, None] = '88006c44f2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('admin_created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['Restaurant.restaurant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_Admin_admin_id'), 'Admin', ['admin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Admin_admin_id'), table_name='Admin')
    op.drop_table('Admin')
    # ### end Alembic commands ###
